sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker pull moorviper/dockerlatex
install:
script:
  - bash build.sh
deploy:
  provider: releases
  api_key:
    secure: aEeNXJVI9ClUsFndD3/lbE/524TSsSzpxzI47+CTXWgrkAbQiGGpVNsKp1Slbsehvj0nkdZyATtbkGYWBKjJ9H2/dzRGAoZS++Jom/onMBnFU+BA2/IZHPutt2cK938EFo8DRqM2Xs5lAawTr4zxDyDY63XR7B0ekZcf4yxRTc1cdxmCL/iYAA4Si949Xg8J/uzBEYub/2l4N679iEer7P14mFdZGcSe+4aO9pTu8RuhhoPB0tbyTgO3UQZiLW7qRPuuSD1uVGCTQFPkGqynv+u/im6iuA+yuMQxRTKnsk8KPPlDm/tyU5rZo8DF8NwlxuD/lzOJo/gK3LxOuBqHKNi6oRtuGsV248LxKN4pdAODIcUZTyAIu3AD62P+LG52S+iaURSBpSlAg8PIrbU3AyKFWbIgDwf8L2BdCNZL/PGd258zqjbOR/S2kGqMMD5vknXRN4Q5ByIW5t+ouxBxY3Xf4XW9ZU7iP7QSfKD1ilzpP738mJ6uiDJvGQ0oGYB3g6Mw4RNKX97a2kjVWeDELtgpgspGISXkDwq8368sYFQol7t2BhnP/z3yLJpKcEOx+le+XW8/EqseZkAWf6BhKJEShrbw0rKAuMuv5WtpoKhgNrIGcsGhw4IUkFXqTWOmamzrYGHsgolwgmRCe7FOEB3396AhmwOdpsQCec4Wf1w=
  file: anleitungen.tar.bz2
  skip_cleanup: true
  on:
    repo: Moorviper/Freifunk-Router-Anleitungen
    tags: true
    all_branches: true
